server:
  port: 5000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/yaojin156/tmp.git
#          force-pull: true
        ##定义去拉取配置的地址
          uri: D:\\work\\demo\\lesson-3\\config-server\\src\\main\\resources\\configs


management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  application:
#    name: app-provider-config
#  cloud:
#    config:
#      enabled: true
#      server:
#        svn:
#          uri: http://ip:port/svn/mogo/Coding/app-hotpoint-parent/app-global-config
#          username: username
#          password: password
#          default-label: config-repo
#  profiles:

#    active: subversion
